const menu = [
  {
    id: 1,
    title: 'non fasting combo',
    category: 'lunch',
    price: 250,
    img: './images/combo.jpg',
    desc: `A delicious combination of different  dishes `,
  },
  {
    id: 2,
    title: 'Vegie Combo',
    category: 'lunch',
    price: 150,
    img: './images/mesob vegie.jpg',
    desc: `A delicious combination of different vigan dishes `,
  },
  {
    id: 3,
    title: 'Quanta Fitfit',
    category: 'lunch',
    price: 95,
    img: './images/quanta firfir.jpg',
    desc: `Dried, fried meat made with a sauce with engera mixed  `,
  },
  {
    id: 4,
    title: 'Derho',
    category: 'lunch',
    price: 180,
    img: './images/dorowet.jpg',
    desc: `A national favourite of Ethiopia and Eritrea, stewed marinated chicken on the bone cooked with a mild spiced
    onion, tomato-based sauce, served with a hard-boiled egg. `,
  },
  {
    id: 5,
    title: 'Kicha Fitfit/Chechebsa',
    category: 'breakfast',
    price: 80,
    img: './images/kicha ftft.jpg',
    desc: `Small piece of flatbread braised with Berber and your choice of Ethiopian butter or Olive Oil/yoghurt and egg to make your chechebsa extra special `,
  },
  {
    id: 6,
    title: 'Tibs',
    category: 'lunch',
    price: 18.99,
    img: './images/tibs.jpg',
    desc: `Cubed lean beef plate, seasoned with onion, kibay, green peppers, and minced rosemary. Served on a sizzling hot plate`,
  },
  {
    id: 7,
    title: 'Tibs firfir',
    category: 'breakfast',
    price: 75,
    img: './images/tibsfirfir.jpg',
    desc: `Bits of Injera soaked in spiced berbere sauce and topped with scrambled eggs `,
  },
  {
    id: 8,
    title: 'Ful meselah',
    category: 'breakfast',
    price: 12.99,
    img: './images/ful.jpg',
    desc: `Crushed Beans sauteed with our spices and garnished with fresh diced onions, tomato, and pepper.Served with egg and ayib or yoghurt`,
  },
  {
    id: 9,
    title: 'Mies',
    category: 'drinks',
    price: 6.99,
    img: './images/mies.jpg',
    desc: `Eritrean and Ethiopian fine honey wine made locally`,
  },
  {
    id: 10,
    title: 'Tropical',
    category: 'shakes',
    price: 16.99,
    img: './images/tropical.jpg',
    desc: `a mixiture of different fruits juice made for a beautiful drink`,
  },
  {
    id: 11,
    title: 'Chocolate',
    category: 'shakes',
    price: 16.99,
    img: './images/choco.jpg',
    desc: `a great chocolate mix with milk and a scoop of ice creame with orea toppings`,
  },
  {
    id: 12,
    title: 'Suwa',
    category: 'drinks',
    price: 8.99,
    img: './images/suwa.jpg',
    desc: `Habesha delicacy drink favoured by many.`,
  },
  {
    id: 13,
    title: 'Areqi',
    category: 'drinks',
    price: 12.99,
    img: './images/zebib.jpg',
    desc: `Habesha vodka made and filtered carefully locally.`,
  },
  {
    id: 14,
    title: 'Tradional coffee',
    category: 'drinks',
    price: 4.99,
    img: './images/coffee.jpg',
    desc: `Beautiful coffee made by the traditional coffee cermony celebrated in Ethiopia and Eritrea.`,
  },
];
export default menu;
